### ISSUE TITLE
Proposal: new keys format customizable key prefixes 

### ISSUE THREAD

**Issue by infinidi** [EOSIO/fc#18]
Since there is interest in customizing key prefixes, allow for specifying custom prefixes at compile time.

* No impact on default behavior
* Use **new** (PUB_K1_xxxx) not legacy  (EOSxxxx) format
* Enhance build logic so that new format can be used to allow for custom keys such as MYSYM_K1_ instead of PUB_K1_
* Both MYSYM_K1_ and PUB_K1_ will be accepted by the system since the actual number past prefix is unaffected
* Default "PUB" will be replaced with "MYSYM" (for example) at compile time (see: public_key_base_prefix https://github.com/EOSIO/fc/blob/df5a17ef0704d7dd96c444bfd9a70506bcfbc057/include/fc/crypto/public_key.hpp)
* Treat encryption marker K1|R1 or others in the future separately, no change (ref: https://github.com/EOSIO/eos/pull/2441)
* Same customization for SIG and PVT prefixes if desired.
* Custom symbols will be passed at compile time for different chains

@tbfleming, @jgiszczak, @heifner: Since there is a fair amount of conversation on this subject already https://github.com/eosio/eos/issues/5467, submitting a proposal first, I can do a PR if there is general acceptance and/or suggestions of course.

Cheers,
Dmitri

**Comment by infinidi** [comment]
@tbfleming - thank you for looking at this so quickly! 

Just to add a bit for a complete picture: I agree with the points in EOSIO/eos#5467 including: "Tools, libraries, api endpoints, etc. will not support custom prefixes for the legacy format. Instead, users may use conversion tools.". 

I'm only quoting the "previous" conversation as a desire for "some kind" of customization - I agree with your points there.

What I'm looking at is small "addition" to how the *new* format is handled within fc. While "all" the tools and libraries can/will use the new "PUB_K1_" format and contents, just add the capability of using a "custom" prefix like "MYSYM_K1", effectively simply swapping out "PUB" with "MYSYM" and making so that that both "MYSYM_K1" and "PUB_K1" will be accepted "at the same time" but let's say just "MYSYM_K1" is  "generated" at key creation. Seems like a doable compromise. 

This proposal is not arguing for changing the legacy format "contents", or changing the format and/or any functionality with "PUB_K1_" prefix as it might also be important for chain compatibility. It suggests making the *new* format flexible with regards to "contents" of the prefix as prefix does not affect the crypto aspects itself.

I have not really seen this *additional* option being discussed yet, while it looks like there are even some early provisions in the code for it ("PUB", "PVT" and "SIG" are arguably configurable themselves and are not completely hard-coded already).

Cheers,
Dmitri

**Comment by tbfleming** [comment]
Again, we will not support customizable key prefixes.

**Comment by tbfleming** [comment]
The purpose of a key prefix is to identify the key format. Going forward, brands will not be a part of the key format, except for backwards compatibility with the `EOS` prefix.

**Comment by infinidi** [comment]
Thank you for the clarification @tbfleming, especially for the stating the idea of the purpose of the format and its functions!

Cheers,
Dmitri
